# Setup
title:        Test jekyll
tagline:      Description
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Luisa
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown